language: android
jdk: oraclejdk8
sudo: false

notifications:
    email:
        - privyfinder@gmail.com

env:
    global:
        - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

android:
    update_sdk: true
    components:
        - platform-tools
        - tools
        - build-tools-25.0.1
        - android-25

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

before_script:
    - chmod +x gradlew      #Grand permissions

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - gradlew build
  

before_install:
    - pip install --user codecov    #Install codecov

after_success:
    - codecov -t a2d569ed-e94b-4f97-8df9-2ad1316d89d9        #Run codecov

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
